language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
gemfile:
  - Gemfile
services: -postgresql
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
env:
  global:
    - PGHOST=""
before_install: gem install bundler -v 2.1.4
script:
  - bundle exec rake compile
  - cd test/dummy
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake test
