language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
gemfile:
  - Gemfile
services: -postgresql
addons:
  postgresql: 12
  apt:
    packages:
      - postgresql-12-postgis-3
      - postgresql-12-postgis-3-scripts
      - postgresql-client-12
env:
  global:
    - PGHOST=""
before_install: gem install bundler -v 2.1.4
script:
  - cd test/dummy
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake test
